/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacegrafica;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import opencv.ExtratorImagem;
import weka.classifiers.Classifier;
import weka.classifiers.bayes.NaiveBayes;
import weka.classifiers.functions.LibSVM;
import weka.classifiers.functions.MultilayerPerceptron;
import weka.classifiers.lazy.IBk;
import weka.classifiers.rules.JRip;
import weka.classifiers.rules.OneR;
import weka.classifiers.trees.J48;
import weka.core.DenseInstance;
import weka.core.Instance;
import weka.core.Instances;
import weka.core.SelectedTag;
import weka.core.converters.ConverterUtils.DataSource;

/**
 *
 * @author Jones
 */
public class Preditor extends javax.swing.JFrame {

    private Instances instancias;

    public Preditor() {
        initComponents();
    }

    public void classifica() throws Exception {
        NaiveBayes nb = new NaiveBayes();
        nb.buildClassifier(instancias);

        J48 arvore = new J48();
        arvore.buildClassifier(instancias);

        OneR oner = new OneR();
        JRip jrip = new JRip();
        oner.buildClassifier(instancias);
        jrip.buildClassifier(instancias);

        IBk ibk = new IBk(3);
        ibk.buildClassifier(instancias);

        LibSVM svm = new LibSVM();
        svm.setKernelType(new SelectedTag(LibSVM.KERNELTYPE_LINEAR,
                LibSVM.TAGS_KERNELTYPE));
        svm.buildClassifier(instancias);

        MultilayerPerceptron multi = new MultilayerPerceptron();
        multi.buildClassifier(instancias);

        // Criação de novo registro
        Instance novo = new DenseInstance(instancias.numAttributes());
        novo.setDataset(instancias);
        novo.setValue(0, Float.parseFloat(lblLaranjaBart.getText()));
        novo.setValue(1, Float.parseFloat(lblAzulCalcao.getText()));
        novo.setValue(2, Float.parseFloat(lblAzulSapato.getText()));
        novo.setValue(3, Float.parseFloat(lblMarromHomer.getText()));
        novo.setValue(4, Float.parseFloat(lblAzulHomer.getText()));
        novo.setValue(5, Float.parseFloat(lblSapatoHomer.getText()));

        // Previsão
        double resultadoNaive[] = nb.distributionForInstance(novo);
        DecimalFormat df = new DecimalFormat("#,###.0000");
        lblNaiveBart.setText("Bart: " + df.format(resultadoNaive[0]));
        lblNaiveHomer.setText("Homer: " + df.format(resultadoNaive[1]));

        // Previsão
        double resultadoJ48[] = arvore.distributionForInstance(novo);
        lblJ48Bart.setText("Bart: " + df.format(resultadoJ48[0]));
        lblJ48Homer.setText("Homer: " + df.format(resultadoJ48[1]));

        // Previsão
        double resultadoOneR[] = oner.distributionForInstance(novo);
        double resultadoJRip[] = jrip.distributionForInstance(novo);
        lblOneRBart.setText("Bart: " + df.format(resultadoOneR[0]));
        lblOneRHomer.setText("Homer: " + df.format(resultadoOneR[1]));
        lblJRipBart.setText("Bart: " + df.format(resultadoJRip[0]));
        lblJRipHomer.setText("Homer: " + df.format(resultadoJRip[1]));

        double resultadoIbk[] = ibk.distributionForInstance(novo);
        lblIBkBart.setText("Bart: " + df.format(resultadoIbk[0]));
        lblIBkHomer.setText("Homer: " + df.format(resultadoIbk[1]));

        // Previsão LibSVM
        double resultadoSVM[] = svm.distributionForInstance(novo);
        lblSVMBart.setText("Bart: " + df.format(resultadoSVM[0]));
        lblSVMHomer.setText("Homer: " + df.format(resultadoSVM[1]));

        // Previsão MultiLayerPerceptron
        double resultadoMultiLayer[] = multi.distributionForInstance(novo);
        lblMultiLayerBart.setText("Bart: " + df.format(resultadoMultiLayer[0]));
        lblMultiLayerHomer.setText("Homer: " + df.format(resultadoMultiLayer[1]));
    }

    public void carregaBaseWeka() throws Exception {
        DataSource ds = new DataSource("src\\opencv\\caracteristicas.arff");
        instancias = ds.getDataSet();
        instancias.setClassIndex(instancias.numAttributes() - 1);
        //System.out.println(instancias.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelecionarImagem = new javax.swing.JButton();
        txtCaminhoImagem = new javax.swing.JTextField();
        lblImagem = new javax.swing.JLabel();
        btnExtrairCaracteristicas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLaranjaBart = new javax.swing.JLabel();
        lblAzulCalcao = new javax.swing.JLabel();
        lblAzulSapato = new javax.swing.JLabel();
        lblAzulHomer = new javax.swing.JLabel();
        lblMarromHomer = new javax.swing.JLabel();
        lblSapatoHomer = new javax.swing.JLabel();
        btnClassificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblNaiveBart = new javax.swing.JLabel();
        lblNaiveHomer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblJ48Bart = new javax.swing.JLabel();
        lblJ48Homer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblOneRBart = new javax.swing.JLabel();
        lblOneRHomer = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblJRipBart = new javax.swing.JLabel();
        lblJRipHomer = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblIBkBart = new javax.swing.JLabel();
        lblIBkHomer = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSVMBart = new javax.swing.JLabel();
        lblSVMHomer = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMultiLayerBart = new javax.swing.JLabel();
        lblMultiLayerHomer = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSelecionarImagem.setText("Selecionar imagem");
        btnSelecionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarImagemActionPerformed(evt);
            }
        });

        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnExtrairCaracteristicas.setText("Extrair características");
        btnExtrairCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtrairCaracteristicasActionPerformed(evt);
            }
        });

        jLabel1.setText("Características do Bart");

        jLabel2.setText("Características do Homer");

        lblLaranjaBart.setText("jLabel3");

        lblAzulCalcao.setText("jLabel4");

        lblAzulSapato.setText("jLabel5");

        lblAzulHomer.setText("jLabel6");

        lblMarromHomer.setText("jLabel7");

        lblSapatoHomer.setText("jLabel8");

        btnClassificar.setText("Classificar");
        btnClassificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassificarActionPerformed(evt);
            }
        });

        jLabel3.setText("Naive Bayes");

        lblNaiveBart.setText("jLabel4");

        lblNaiveHomer.setText("jLabel5");

        jLabel4.setText("J48");

        lblJ48Bart.setText("jLabel5");

        lblJ48Homer.setText("jLabel6");

        jLabel5.setText("OneR");

        lblOneRBart.setText("jLabel6");

        lblOneRHomer.setText("jLabel6");

        jLabel6.setText("JRip");

        lblJRipBart.setText("jLabel7");

        lblJRipHomer.setText("jLabel7");

        jLabel7.setText("IBk");

        lblIBkBart.setText("jLabel8");

        lblIBkHomer.setText("jLabel9");

        jLabel8.setText("SVM");

        lblSVMBart.setText("jLabel9");

        lblSVMHomer.setText("jLabel9");

        jLabel9.setText("Multilayer");

        lblMultiLayerBart.setText("jLabel10");

        lblMultiLayerHomer.setText("jLabel11");

        jButton1.setText("Treinar/gerar modelo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Classificar usando modelo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExtrairCaracteristicas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClassificar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(lblLaranjaBart)
                                    .addComponent(lblAzulCalcao)
                                    .addComponent(lblAzulSapato)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(lblNaiveBart)
                                            .addComponent(lblNaiveHomer))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblJ48Homer)
                                            .addComponent(lblJ48Bart)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7)
                                            .addComponent(lblIBkBart)
                                            .addComponent(lblIBkHomer)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblJRipHomer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(lblJRipBart))))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblSapatoHomer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMarromHomer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAzulHomer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOneRBart)
                                        .addGap(64, 64, 64)
                                        .addComponent(lblSVMBart))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblOneRHomer)
                                        .addGap(64, 64, 64)
                                        .addComponent(lblSVMHomer))
                                    .addComponent(jLabel9)
                                    .addComponent(lblMultiLayerBart)
                                    .addComponent(lblMultiLayerHomer)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSelecionarImagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCaminhoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionarImagem)
                    .addComponent(txtCaminhoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExtrairCaracteristicas)
                            .addComponent(btnClassificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLaranjaBart)
                            .addComponent(lblAzulHomer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAzulCalcao)
                            .addComponent(lblMarromHomer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAzulSapato)
                            .addComponent(lblSapatoHomer))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNaiveBart)
                            .addComponent(lblJ48Bart)
                            .addComponent(lblOneRBart)
                            .addComponent(lblSVMBart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNaiveHomer)
                            .addComponent(lblJ48Homer)
                            .addComponent(lblOneRHomer)
                            .addComponent(lblSVMHomer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJRipBart)
                            .addComponent(lblIBkBart)
                            .addComponent(lblMultiLayerBart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJRipHomer)
                            .addComponent(lblIBkHomer)
                            .addComponent(lblMultiLayerHomer))))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarImagemActionPerformed
        JFileChooser fc = new JFileChooser();
        int retorno = fc.showDialog(this, "Selecione a imagem");
        if (retorno == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();
            txtCaminhoImagem.setText(arquivo.getAbsolutePath());

            BufferedImage imagemBmp = null;
            try {
                imagemBmp = ImageIO.read(arquivo);
            } catch (IOException ex) {
                Logger.getLogger(Preditor.class.getName()).log(Level.SEVERE, null, ex);
            }

            ImageIcon imagemLabel = new ImageIcon(imagemBmp);
            lblImagem.setIcon(new ImageIcon(
                    imagemLabel.getImage().getScaledInstance(lblImagem.getWidth(),
                            lblImagem.getHeight(), Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_btnSelecionarImagemActionPerformed

    private void btnExtrairCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtrairCaracteristicasActionPerformed
        ExtratorImagem extrator = new ExtratorImagem();
        float[] caracteristicas = extrator.extrairCaracteristicasImagem(txtCaminhoImagem.getText());
        lblLaranjaBart.setText(String.valueOf(caracteristicas[0]));
        lblAzulCalcao.setText(String.valueOf(caracteristicas[1]));
        lblAzulSapato.setText(String.valueOf(caracteristicas[2]));
        lblAzulHomer.setText(String.valueOf(caracteristicas[3]));
        lblMarromHomer.setText(String.valueOf(caracteristicas[4]));
        lblSapatoHomer.setText(String.valueOf(caracteristicas[5]));
    }//GEN-LAST:event_btnExtrairCaracteristicasActionPerformed

    private void btnClassificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassificarActionPerformed
        try {
            carregaBaseWeka();
            classifica();
        } catch (Exception ex) {
            Logger.getLogger(Preditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClassificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            carregaBaseWeka();
            J48 j48 = new J48();
            j48.buildClassifier(instancias);

            ObjectOutputStream classificador = new ObjectOutputStream(new FileOutputStream("src/opencv/arvore_treinada.model"));
            classificador.writeObject(j48);
            classificador.flush();
            classificador.close();

        } catch (Exception ex) {
            Logger.getLogger(Preditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int quantidadeHomer = 0, quantidadeBart = 0;
        final double rejeicao = 0.99;
        try {
            ObjectInputStream modeloJ48 = new ObjectInputStream(new FileInputStream("src/opencv/j48.model"));
            J48 j48 = (J48) modeloJ48.readObject();
            modeloJ48.close();

            ObjectInputStream modeloJrip = new ObjectInputStream(new FileInputStream("src/opencv/jrip.model"));
            JRip jrip = (JRip) modeloJrip.readObject();
            modeloJrip.close();

            ObjectInputStream modeloIbk = new ObjectInputStream(new FileInputStream("src/opencv/ibk3.model"));
            IBk ibk = (IBk) modeloIbk.readObject();
            modeloIbk.close();

            // Criação de novo registro
            carregaBaseWeka();
            Instance novo = new DenseInstance(instancias.numAttributes());
            novo.setDataset(instancias);
            novo.setValue(0, Float.parseFloat(lblLaranjaBart.getText()));
            novo.setValue(1, Float.parseFloat(lblAzulCalcao.getText()));
            novo.setValue(2, Float.parseFloat(lblAzulSapato.getText()));
            novo.setValue(3, Float.parseFloat(lblMarromHomer.getText()));
            novo.setValue(4, Float.parseFloat(lblAzulHomer.getText()));
            novo.setValue(5, Float.parseFloat(lblSapatoHomer.getText()));

            // Previsão
            double resultado[] = j48.distributionForInstance(novo);
            DecimalFormat df = new DecimalFormat("#,###.0000");
            System.out.println("J48");
            System.out.println("Bart: " + df.format(resultado[0]));
            System.out.println("Homer: " + df.format(resultado[1]));
            if (resultado[0] > resultado[1]) {
                if (resultado[0] > rejeicao) {
                    quantidadeBart++;
                }
            } else if (resultado[1] > resultado[0]) {
                if (resultado[1] > rejeicao) {
                    quantidadeHomer++;
                }
            } else if (resultado[0] > rejeicao && resultado[1] > rejeicao) {
                quantidadeBart++;
                quantidadeHomer++;
            }

            resultado = jrip.distributionForInstance(novo);
            System.out.println("JRip");
            System.out.println("Bart: " + df.format(resultado[0]));
            System.out.println("Homer: " + df.format(resultado[1]));
            if (resultado[0] > resultado[1]) {
                if (resultado[0] > rejeicao) {
                    quantidadeBart++;
                }
            } else if (resultado[1] > resultado[0]) {
                if (resultado[1] > rejeicao) {
                    quantidadeHomer++;
                }
            } else if (resultado[0] > rejeicao && resultado[1] > rejeicao) {
                quantidadeBart++;
                quantidadeHomer++;
            }

            resultado = ibk.distributionForInstance(novo);
            System.out.println("IBK 3");
            System.out.println("Bart: " + df.format(resultado[0]));
            System.out.println("Homer: " + df.format(resultado[1]));
            if (resultado[0] > resultado[1]) {
                if (resultado[0] > rejeicao) {
                    quantidadeBart++;
                }
            } else if (resultado[1] > resultado[0]) {
                if (resultado[1] > rejeicao) {
                    quantidadeHomer++;
                }
            } else if (resultado[0] > rejeicao && resultado[1] > rejeicao) {
                quantidadeBart++;
                quantidadeHomer++;
            }

            System.out.println("Quantidade Bart: " + quantidadeBart);
            System.out.println("Quantidade Homer: " + quantidadeHomer);

            if (quantidadeBart == 0 && quantidadeHomer == 0) {
                System.out.println("A instância foi rejeitada");
            } else if (quantidadeBart > quantidadeHomer) {
                System.out.println("A classe é Bart");
            } else {
                System.out.println("A classe é Homer");
            }

        } catch (IOException ex) {
            Logger.getLogger(Preditor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Preditor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Preditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassificar;
    private javax.swing.JButton btnExtrairCaracteristicas;
    private javax.swing.JButton btnSelecionarImagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAzulCalcao;
    private javax.swing.JLabel lblAzulHomer;
    private javax.swing.JLabel lblAzulSapato;
    private javax.swing.JLabel lblIBkBart;
    private javax.swing.JLabel lblIBkHomer;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblJ48Bart;
    private javax.swing.JLabel lblJ48Homer;
    private javax.swing.JLabel lblJRipBart;
    private javax.swing.JLabel lblJRipHomer;
    private javax.swing.JLabel lblLaranjaBart;
    private javax.swing.JLabel lblMarromHomer;
    private javax.swing.JLabel lblMultiLayerBart;
    private javax.swing.JLabel lblMultiLayerHomer;
    private javax.swing.JLabel lblNaiveBart;
    private javax.swing.JLabel lblNaiveHomer;
    private javax.swing.JLabel lblOneRBart;
    private javax.swing.JLabel lblOneRHomer;
    private javax.swing.JLabel lblSVMBart;
    private javax.swing.JLabel lblSVMHomer;
    private javax.swing.JLabel lblSapatoHomer;
    private javax.swing.JTextField txtCaminhoImagem;
    // End of variables declaration//GEN-END:variables
}
